### ISSUE TITLE
JSON files updated despite no manual correction

### ISSUE THREAD

**Issue by naga-karthik** [spinalcordtoolbox/manual-correction#7]
I noticed that even when I don't make any changes to the segmentations, the json sidecars get updated with my name. This should be avoided because the jsons should only be updated only when I make some changes to the segmentation (instead of getting updated for just viewing/checking the segmentations for any errors).

**Comment by valosekj** [comment]
Thanks for reporting this!
So, IIUC, you iterated across subjects and modified the segmentation only for some of them, right? If so, this is indeed a case which the script is not prepared for. The reason is that the script assumes that all files provided in the `.yml` need at least some corrections.

**Comment by naga-karthik** [comment]
> So, IIUC, you iterated across subjects and modified the segmentation only for some of them, right?

Yes, I checked them and saw that they were alright, and I don't need to do any changes.

**Comment by naga-karthik** [comment]
Is it because the .yml file is expected to be that of failed cases only?

**Comment by valosekj** [comment]
> Is it because the .yml file is expected to be that of failed cases only?

Exactly!

**Comment by naga-karthik** [comment]
I guess we should label it `won't fix` for now
